adjust eslint, connect tailwindcss

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -2,18 +2,18 @@
 . "$(dirname -- "$0")/_/husky.sh"
 
 # Check tsconfig standarts
-npm run check-types || (echo "❌😂❌ Failed Type check. ❌😂❌ Are you seriously trying to write that? Make the changes required above." false;)
+npm run check-types || ( echo "❌😂❌ Failed Type check. ❌😂❌ Are you seriously trying to write that? Make the changes required above." false;)
 
 # Check Prettier standarts
-npm run check-format || (echo "❌🤮😵‍💫 Its F**KING RAW - Your styling looks disgusting. 😵‍💫🤮❌ Prettier check failed. Run yarn format, add changes and try again." false;)
+npm run check-format || ( echo "❌🤮😵‍💫 Its F**KING RAW - Your styling looks disgusting. 😵‍💫🤮❌ Prettier check failed. Run yarn format, add changes and try again." false;)
 
 # Check ESLint standarts
-npm run check-lint || (echo "❌🤮😵‍💫 Get that weak s**t out of here. 😵‍💫🤮❌ ESLint check failed. Make the required changes listed above, add changes and try to commit again" false;)
+npm run check-lint || ( echo "❌🤮😵‍💫 Get that weak s**t out of here. 😵‍💫🤮❌ ESLint check failed. Make the required changes listed above, add changes and try to commit again" false;)
 
 # If everything passes... try to run a build
 echo "🤔🤔🤔 ...Alright... Code looks good to me... Trying to build now 🤔🤔🤔"
 
-npm run build || (echo "❌⛑️🔨 Better call Bob... Because your build failed 🔨⛑️❌ Next build failed: View the errors above to see why" false;)
+npm run build || ( echo "❌⛑️🔨 Better call Bob... Because your build failed 🔨⛑️❌ Next build failed: View the errors above to see why" false;)
 
 # If it builds we can commit 
 echo "✅✅✅ You win this time... I am commiting this now ✅✅✅"
